Домашнее залание к уроку 1
idoleg/react-01.06 pull request #12
Opened 2020-06-04 08:09 UTC by komalapa

2020-06-05 07:20 UTC, SerSerch commented on AliceKuzmenko/package.json
> +    "webpack-dev-server": "^3.11.0"
сервер нужно перенести в devDependencies
и еще ошибочные модули установились (первые два)

2020-06-05 09:05 UTC, idoleg requested changes

2020-06-05 09:05 UTC, idoleg commented on AliceKuzmenko/src/index.js
> +      );
На втором уроке мы разбираем правильную реализацию данного функционала

2020-06-05 09:05 UTC, idoleg commented on AliceKuzmenko/package.json
> +    "webpack-dev-server": "^3.11.0"
Да, жду исправления

2020-06-08 06:07 UTC, komalapa commented
Добрый день. Исправила установку сервера.

2020-06-14 07:32 UTC, idoleg approved these changes
Без замечаний

2020-06-14 07:32 UTC, merged