ReactJS Lesson #5 Daniil Lyadnov
idoleg/react-01.06 pull request #40
Opened 2020-06-10 15:21 UTC by websterday-online

2020-06-14 08:03 UTC, idoleg requested changes
Поправить конфликт и я прийму

2020-06-14 08:03 UTC, idoleg commented on .gitignore
> +.idea
Отмените эти изменений, конфликт

2020-06-21 19:31 UTC, websterday-online commented
Доброй ночи, я не пойму, как правильно сдавать ДЗ.
Я постоянно делаю что то не так, как работать с гит я знаю, но не понимаю как лучше всего с ним работать. Как правильно сдавать ДЗ, что бы не трогать ваш код и что бы правильно делать Пулл реквест. А сейчас уже почти конец курса и я еще больше запутался, а после того раза как я у вас там что то заменил, еще больше начал переживать(

2020-07-07 10:32 UTC, idoleg commented
> Доброй ночи, я не пойму, как правильно сдавать ДЗ.
> Я постоянно делаю что то не так, как работать с гит я знаю, но не понимаю как лучше всего с ним работать. Как правильно сдавать ДЗ, что бы не трогать ваш код и что бы правильно делать Пулл реквест. А сейчас уже почти конец курса и я еще больше запутался, а после того раза как я у вас там что то заменил, еще больше начал переживать(

Вы сейчас учитесь, так что ничего нет страшного, я вас не осуждаю за то, что вы мой код чуть поправили :)
Просто вам нужно быть внимательнее и смотреть, какие, изменения попадают в ваш коммит.

2020-07-07 10:33 UTC, idoleg approved these changes
Без замечаний

2020-07-07 10:33 UTC, merged