Ivan Alenin - request fo 1-st lesson
idoleg/react-01.06 pull request #5
Opened 2020-06-03 13:49 UTC by aiscorp

2020-06-03 16:22 UTC, aiscorp commented
1. Прошу посмотреть в чем у меня ошибка сейчас с классовыми компонентами: они должны передавать между собой текстовое сообщение через родителя, но у меня никак не получается понять в чем причина падений. 
2. В текущей реализации InputBlock получает метод чтения сообщения от родителя App, затем App формирует состояние MessageGroup в зависимости тот того есть сообщение или нет, устанавливая в true флаг наличия сообщения. Не работает, частями работает как нужно. Где-то тупые ошибки.

2020-06-03 22:42 UTC, aiscorp commented
Удалось добиться задуманного содержания.
Будет интересно получить ваше ревью и критику.

2020-06-05 07:37 UTC, SerSerch commented on IvanAlenin/package.json
> +    "html-inline-css-webpack-plugin": "^1.8.0",
autoprefixer
grep
html-inline-css-webpack-plugin
в devDependencies

2020-06-05 09:15 UTC, idoleg requested changes
Необходимо отменить изменения .gitignore

2020-06-06 09:23 UTC, aiscorp commented
> Необходимо отменить изменения .gitignore

Исправлено это и правки выше.

2020-06-14 07:31 UTC, merged